# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

$LOAD_PATH.unshift "../lib"
$LOAD_PATH.unshift "../../lib"
require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

desc "Create mo-files for L10n"
task :makemo do
  require 'gettext_rails/tools'
  GetText.create_mofiles
  mkdir "log" unless File.exists? "log"
end

desc "Update pot/po files to match new version."
task :updatepo do
  require 'gettext_rails/tools'
  GetText.update_pofiles("rails_test", Dir.glob("{app,lib}/**/*.{rb,rhtml,erb}"),
                         "rails_test 1.2.0")
end


